<br>

<form action="<?=BASE_URL?>?page=calc" method="post">
        <input type="text" name="arg1" size="5" value="<?=$arg1?>">
        <input type="submit" name="operation" value="add">
        <input type="submit" name="operation" value="sub">
        <input type="submit" name="operation" value="mul">
        <input type="submit" name="operation" value="div">
        <input type="text" name="arg2" size="5" value="<?=$arg2?>">
        =
        <input type="text" readonly size="15" value="<?=$result?>">

    </form>
