<?php if ($success === "0"):?>
    <p style="color:red">Заполните все поля!</p>
<?php endif;?>

<h2>Создать пост</h2>
<form action="" method="post">
    Заголовок поста:<br>
    <input type="text" name="title"><br><br>
    Категория:<br>
    <select name="category_id">
        <?php foreach ($categories as $category):?>
            <option value="<?=$category['id']?>"><?=$category['name']?></option>
        <?php endforeach;?>
    </select><br><br>
    Текст поста:<br>
    <textarea name="text" cols="30" rows="3"></textarea><br>
    <input type="submit" value="Добавить">
</form>